<!--=============================================
=            Include JavaScript files           =
==============================================-->

<!-- jQuery V3.4.1 -->
<script src="../agenda_mvc/web/js/jquery-3.4.1.min.js" ></script>

<!-- popper -->
<script src="../agenda_mvc/web/js/popper.min.js" ></script>

<!-- Bootstrap V4.3 -->
<script src="../agenda_mvc/web/js/bootstrap.min.js" ></script>

<!-- jQuery Custom Content Scroller V3.1.5 -->
<script src="../agenda_mvc/web/js/jquery.mCustomScrollbar.concat.min.js" ></script>

<!-- Bootstrap Material Design V4.0 -->
<script src="../agenda_mvc/web/js/bootstrap-material-design.min.js" ></script>

<script>$(document).ready(function() { $('body').bootstrapMaterialDesign(); });</script>

<script src="../agenda_mvc/web/js/js.js" ></script>

<!-- Sweet Alert V8.13.0 JS file-->
<script src="../agenda_mvc/web/js/sweetalert2.min.js" ></script>

<!--=============================================
=            Include CSS files           =
==============================================-->

<!-- Normalize V8.0.1 -->
<link rel="stylesheet" href="../agenda_mvc/web/css/normalize.css">

<!-- Bootstrap V4.3 -->
<link rel="stylesheet" href="../agenda_mvc/web/css/bootstrap.min.css">

<!-- Bootstrap Material Design V4.0 -->
<link rel="stylesheet" href="../agenda_mvc/web/css/bootstrap-material-design.min.css">

<!-- Font Awesome V5.9.0 -->
<link rel="stylesheet" href="../agenda_mvc/web/css/all.css">

<!-- Sweet Alerts V8.13.0 CSS file -->
<link rel="stylesheet" href="../agenda_mvc/web/css/sweetalert2.min.css">

<!-- jQuery Custom Content Scroller V3.1.5 -->
<link rel="stylesheet" href="../agenda_mvc/web/css/jquery.mCustomScrollbar.css">

<!-- General Styles -->
<link rel="stylesheet" href="../agenda_mvc/web/css/style.css">